force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Contact_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Contact_Compensation__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT SUBMITTED</fullName>
                <default>true</default>
                <label>NOT SUBMITTED</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testPreventUpdateSubmitted.cls
@isTest
public class testPreventUpdateSubmitted {
	
    static testmethod void testPreventUpdateSubmitted(){
        Contact c = new Contact(LastName='LastName');
        insert c;
        Compensation__c cmp = new Compensation__c(Name='Compensation-',
                                         Contact_Compensation__c = c.Id,
                                         Created_Date__c = Date.today());
        cmp.Submitted__c = True;
        cmp.Status__c = 'SUBMITTED';
        insert cmp;
        Test.startTest();
        try{
            cmp.Submitted__c = False;
            update cmp;
        }catch(DMLexception e){
            system.assert(e.getMessage() != null);
        }
        Test.stopTest();
    }
}